/** @type {import('tailwindcss').Config} */
const tailwindConfig = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        "on-background": "#e5e2e1",
        "on-surface-variant": "#cfc2d6",
        "on-primary-container": "#400071",
        "inverse-surface": "#e5e2e1",
        "on-primary-fixed-variant": "#6900b3",
        tertiary: "#00daf3",
        "surface-container-lowest": "#0e0e0e",
        "surface-dim": "#131313",
        "secondary-fixed": "#d8e2ff",
        "surface-variant": "#353534",
        "inverse-primary": "#842bd2",
        "tertiary-fixed-dim": "#00daf3",
        "error-container": "#93000a",
        "on-secondary-container": "#e6ecff",
        "secondary-fixed-dim": "#adc6ff",
        "primary-fixed-dim": "#ddb7ff",
        outline: "#988d9f",
        "on-surface": "#e5e2e1",
        "on-error-container": "#ffdad6",
        "on-primary": "#490080",
        primary: "#ddb7ff",
        background: "#131313",
        "surface-container": "#201f1f",
        secondary: "#adc6ff",
        "tertiary-container": "#009fb2",
        "outline-variant": "#4d4354",
        "on-tertiary-fixed": "#001f24",
        "on-secondary-fixed": "#001a42",
        "surface-container-high": "#2a2a2a",
        "inverse-on-surface": "#313030",
        "on-tertiary": "#00363d",
        "on-tertiary-fixed-variant": "#004f58",
        "on-primary-fixed": "#2c0051",
        "primary-container": "#b76dff",
        "secondary-container": "#0566d9",
        "on-error": "#690005",
        "surface-container-low": "#1c1b1b",
        "on-tertiary-container": "#002f35",
        error: "#ffb4ab",
        "on-secondary-fixed-variant": "#004395",
        "on-secondary": "#002e6a",
        "tertiary-fixed": "#9cf0ff",
        surface: "#131313",
        "primary-fixed": "#f0dbff",
        "surface-tint": "#ddb7ff",
        "surface-container-highest": "#353534",
        "surface-bright": "#3a3939",
      },
      fontFamily: {
        headline: ["var(--font-headline)"],
        body: ["var(--font-body)"],
        label: ["var(--font-body)"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
};

export default tailwindConfig;

